[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]
options = ["--edition", "2024"]

[formatter.scheme]
command = "schemat"
includes = ["*.scm"]
