[package]
edition = "2024"
name = "webschembly-runtime-rust"
version = "0.1.0"

[dependencies]
log = {workspace = true}
rustc-hash = {workspace = true}
webschembly-compiler = {path = "../webschembly-compiler"}

[lib]
crate-type = ["cdylib"]
test = false
