name: autofix
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  autofix:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/setup
      - name: Run autofix
        run: |
          treefmt
          cargo clippy --all --lib --tests --fix --allow-dirty --allow-staged
      - name: Git Diff
        id: git-diff
        run: git diff --exit-code || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and Push
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: auto-fix format and lint"
          git push
